version: '3'

services:
    phoenix:
        build:
            context: .
        environment:
            PGUSER: postgres
            PGPASSWORD: postgres
            PGDATABASE: club_backend_dev
            PGPORT: 5432
            PGHOST: db
        ports:
            - "4000:4000"
        volumes:
            - ./lib:/app/lib
        depends_on:
            - db
    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - pgdata:/var/lib/postgresql/data/pgdata

volumes:
    pgdata:
